export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_USERS = "GET_USERS";
export const CATEGORY = "CATEGORY";
export const ORDERS = "ORDERS";
export const ORDER_DETAIL = "ORDER_DETAIL";
export const DETAIL = "DETAIL";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const PRICE_FILTER_ASC = "PRICE_FILTER_ASC";
export const PRICE_FILTER_DES = "PRICE_FILTER_DES";
export const GENDER_FILTER = "GENDER_FILTER";
export const POST_ITEM = "POST_ITEM" ; 
export const NAVEGACION = "NAVEGACION" ; 
export const ENVIAR_CARRITO_AL_BACKEND= 'ENVIAR_CARRITO_AL_BACKEND' 
export const PRODUCT_ERROR= 'PRODUCT_ERROR'




export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FILTER_GENDER = "FILTER_GENDER"
export const PRICE_FILTER = "PRICE_FILTER"

export const UPDATE_GENDER_FILTER = 'UPDATE_GENDER_FILTER';
export const UPDATE_CATEGORY_FILTER = "UPDATE_CATEGORY_FILTER"
export const UPDATE_PRICE_FILTER = "UPDATE_PRICE_FILTER"